# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models


def set_old_logs_as_reported(apps, *args, **kwargs):
    CronJobLog = apps.get_model('django_cron', 'CronJobLog')
    CronJobLog.objects.update(failure_reported=True)


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_cron', '0002_remove_max_length_from_CronJobLog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjoblog',
            name='failure_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_old_logs_as_reported, reverse_code=noop)
    ]
